#!/usr/bin/env bash
set -euo pipefail

umask 077

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COMPOSE_FILE="$SCRIPT_DIR/docker-compose.yml"
SECRETS_DIR="$SCRIPT_DIR/secrets"
RUNTIME_DIR="$SECRETS_DIR/runtime"
RELEASE_ENV="$SECRETS_DIR/release.env"
DEFAULTS_ENV="$SCRIPT_DIR/release.env.example"

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'Missing required command: %s\n' "$1" >&2
    exit 1
  }
}

read_required() {
  local prompt="$1"
  local value=""
  while [[ -z "$value" ]]; do
    read -r -p "$prompt" value
  done
  printf '%s' "$value"
}

read_default() {
  local key="$1"
  awk -v key="$key" 'index($0, key "=") == 1 { print substr($0, length(key) + 2); exit }' "$DEFAULTS_ENV"
}

require_command docker
require_command openssl
require_command awk
docker compose version >/dev/null

if [[ "${EUID}" -ne 0 ]]; then
  printf '%s\n' 'Run this script as root (for example: sudo bash setup.sh).' >&2
  exit 1
fi

if [[ -e "$RELEASE_ENV" ]]; then
  printf 'Existing installation found at %s. Refusing to overwrite it.\n' "$RELEASE_ENV" >&2
  exit 1
fi

printf '%s\n' 'AI Canvas Cloud single-host setup'
printf '%s\n' 'Only the two domain names are required. Enter them without https://.'

PUBLIC_DOMAIN="$(read_required 'Public domain: ')"
ADMIN_DOMAIN="$(read_required 'Admin domain: ')"
APP_IMAGE_SOURCE="$(read_default APP_IMAGE_SOURCE)"
APP_IMAGE_ARCHIVE="$(read_default APP_IMAGE_ARCHIVE)"
APP_LOCAL_IMAGE="$(read_default APP_LOCAL_IMAGE)"

for value in "$PUBLIC_DOMAIN" "$ADMIN_DOMAIN"; do
  if [[ ! "$value" =~ ^[A-Za-z0-9.-]+$ ]]; then
    printf 'Domain contains unsupported characters: %s\n' "$value" >&2
    exit 1
  fi
done
if [[ "$APP_IMAGE_SOURCE" != "archive" ]]; then
  printf '%s\n' 'The bundled single-host installer requires APP_IMAGE_SOURCE=archive.' >&2
  exit 1
fi
if [[ -z "$APP_IMAGE_ARCHIVE" || ! "$APP_IMAGE_ARCHIVE" =~ ^[A-Za-z0-9._-]+$ ]]; then
  printf '%s\n' 'The local image archive name is invalid.' >&2
  exit 1
fi
if [[ -z "$APP_LOCAL_IMAGE" || ! "$APP_LOCAL_IMAGE" =~ ^[A-Za-z0-9./:_-]+$ ]]; then
  printf '%s\n' 'The local image name is invalid.' >&2
  exit 1
fi
if [[ ! -f "$SCRIPT_DIR/$APP_IMAGE_ARCHIVE" ]]; then
  printf 'Missing local image archive: %s\n' "$SCRIPT_DIR/$APP_IMAGE_ARCHIVE" >&2
  printf '%s\n' 'Upload the image archive beside setup.sh, then retry.' >&2
  exit 1
fi

mkdir -p "$RUNTIME_DIR" "$SCRIPT_DIR/backups"
chmod 700 "$SECRETS_DIR" "$RUNTIME_DIR" "$SCRIPT_DIR/backups"
: >"$RUNTIME_DIR/public.env"
: >"$RUNTIME_DIR/admin.env"
chmod 600 "$RUNTIME_DIR/public.env" "$RUNTIME_DIR/admin.env"

random_hex() {
  openssl rand -hex "$1"
}

random_base64() {
  openssl rand -base64 "$1" | tr -d '\n'
}

POSTGRES_PASSWORD="$(random_hex 24)"
REDIS_PASSWORD="$(random_hex 24)"
BETTER_AUTH_SECRET="$(random_hex 32)"
ADMIN_BETTER_AUTH_SECRET="$(random_hex 32)"
OBJECT_STORAGE_KEY="$(random_base64 32)"
SMTP_KEY="$(random_base64 32)"
ASSET_MAINTENANCE_TOKEN="$(random_hex 32)"
POSTGRES_DB="ai_canvas_cloud_production"
POSTGRES_USER="ai_canvas_cloud_owner"
DATABASE_OWNER_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
REDIS_URL="redis://:${REDIS_PASSWORD}@redis:6379/0"

cat >"$RELEASE_ENV" <<EOF
# Generated by setup.sh. Keep this file on the server only.
NODE_ENV=production
DEPLOYMENT_ENV=production
LOG_LEVEL=info
APP_IMAGE_SOURCE=${APP_IMAGE_SOURCE}
APP_IMAGE_ARCHIVE=${APP_IMAGE_ARCHIVE}
APP_LOCAL_IMAGE=${APP_LOCAL_IMAGE}
APP_IMAGE=

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
MIGRATION_DATABASE_URL=${DATABASE_OWNER_URL}
APP_DATABASE_ROLE=ai_canvas_cloud_app
DATABASE_URL=${DATABASE_OWNER_URL}
ADMIN_DATABASE_ROLE=ai_canvas_cloud_admin
ADMIN_DATABASE_URL=${DATABASE_OWNER_URL}

REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=${REDIS_URL}

WEB_PUBLIC_URL=https://${PUBLIC_DOMAIN}
BETTER_AUTH_URL=https://${PUBLIC_DOMAIN}
WEB_ALLOWED_ORIGINS=https://${PUBLIC_DOMAIN}
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}

ADMIN_WEB_PUBLIC_URL=https://${ADMIN_DOMAIN}
ADMIN_WEB_ALLOWED_ORIGINS=https://${ADMIN_DOMAIN}
ADMIN_BETTER_AUTH_URL=https://${ADMIN_DOMAIN}
ADMIN_BETTER_AUTH_SECRET=${ADMIN_BETTER_AUTH_SECRET}
ASSET_MAINTENANCE_TOKEN=${ASSET_MAINTENANCE_TOKEN}

OBJECT_STORAGE_ENVIRONMENT_FALLBACK=false
OBJECT_STORAGE_CREDENTIAL_ACTIVE_KEY_VERSION=1
OBJECT_STORAGE_CREDENTIAL_KEYS={"1":"${OBJECT_STORAGE_KEY}"}

AUTH_EMAIL_TRANSPORT=managed
SMTP_CREDENTIAL_ACTIVE_KEY_VERSION=1
SMTP_CREDENTIAL_KEYS={"1":"${SMTP_KEY}"}
SMTP_HOST=
SMTP_PORT=
SMTP_SECURE=
SMTP_FROM=
SMTP_USERNAME=
SMTP_PASSWORD=

DEPLOYMENT_RESOURCE_NAMESPACE=ai-canvas-cloud-production
DEPLOYMENT_CREDENTIAL_NAMESPACE=ai-canvas-cloud-production-credentials
DATABASE_RESOURCE_ID=ai-canvas-cloud-production-postgres
REDIS_RESOURCE_ID=ai-canvas-cloud-production-redis
S3_RESOURCE_ID=ai-canvas-cloud-production-oss
MAIL_RESOURCE_ID=ai-canvas-cloud-production-mail
PERSISTENCE_RESOURCE_ID=ai-canvas-cloud-production-single-host
DATABASE_CREDENTIAL_ID=ai-canvas-cloud-production-postgres-credential
REDIS_CREDENTIAL_ID=ai-canvas-cloud-production-redis-credential
S3_CREDENTIAL_ID=ai-canvas-cloud-production-oss-credential
MAIL_CREDENTIAL_ID=ai-canvas-cloud-production-mail-credential
EOF
chmod 600 "$RELEASE_ENV"

bash "$SCRIPT_DIR/deploy.sh"

compose() {
  docker compose --env-file "$RELEASE_ENV" -f "$COMPOSE_FILE" "$@"
}

printf '%s\n' 'Create the first super_admin account now.'
compose --profile release run --rm release node scripts/bootstrap-admin.mjs
printf '%s\n' 'Setup complete. Configure OSS in the Admin site, then configure the two Baota sites to proxy to 127.0.0.1:8080 and 127.0.0.1:8081.'
